pre-commit:
  commands:
    lint:
      glob: '*.{ts,js,svelte}'
      run: bunx oxlint --fix {staged_files}
      stage_fixed: true
    format:
      glob: '*.{ts,js,svelte,json,css,md,yml,yaml}'
      run: bunx oxfmt --write {staged_files}
      stage_fixed: true
